modLoader="javafml"
loaderVersion="[47,)"
license="Apache License version 2.0"

[[mods]]
modId="hyblock"
version="1.0.0"
displayName="HyBlockMC"
credits="a mod by callemkay and ignDante. Created using MCreator."
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="callemkay, ignDante"
description="a mod inspired by hypixel skyblock and a continuation/collaboration of Sumptuous Hyperion"

[[dependencies.hyblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.hyblock]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

