
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.hyblockmc.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.hyblockmc.item.YellowmelodyItem;
import net.mcreator.hyblockmc.item.SpiderbootsItem;
import net.mcreator.hyblockmc.item.Song9LockedItem;
import net.mcreator.hyblockmc.item.Song9IncompleteItem;
import net.mcreator.hyblockmc.item.Song9CompleteItem;
import net.mcreator.hyblockmc.item.Song8LockedItem;
import net.mcreator.hyblockmc.item.Song8IncompleteItem;
import net.mcreator.hyblockmc.item.Song8CompleteItem;
import net.mcreator.hyblockmc.item.Song7LockedItem;
import net.mcreator.hyblockmc.item.Song7IncompleteItem;
import net.mcreator.hyblockmc.item.Song7CompleteItem;
import net.mcreator.hyblockmc.item.Song6LockedItem;
import net.mcreator.hyblockmc.item.Song6IncompleteItem;
import net.mcreator.hyblockmc.item.Song6CompleteItem;
import net.mcreator.hyblockmc.item.Song5LockedItem;
import net.mcreator.hyblockmc.item.Song5IncompleteItem;
import net.mcreator.hyblockmc.item.Song5CompleteItem;
import net.mcreator.hyblockmc.item.Song4LockedItem;
import net.mcreator.hyblockmc.item.Song4IncompleteItem;
import net.mcreator.hyblockmc.item.Song4CompleteItem;
import net.mcreator.hyblockmc.item.Song3LockedItem;
import net.mcreator.hyblockmc.item.Song3IncompleteItem;
import net.mcreator.hyblockmc.item.Song3CompleteItem;
import net.mcreator.hyblockmc.item.Song2LockedItem;
import net.mcreator.hyblockmc.item.Song2IncompleteItem;
import net.mcreator.hyblockmc.item.Song2CompleteItem;
import net.mcreator.hyblockmc.item.Song1LockedItem;
import net.mcreator.hyblockmc.item.Song1IncompleteItem;
import net.mcreator.hyblockmc.item.Song1CompleteItem;
import net.mcreator.hyblockmc.item.Song13LockedItem;
import net.mcreator.hyblockmc.item.Song13IncompleteItem;
import net.mcreator.hyblockmc.item.Song13CompleteItem;
import net.mcreator.hyblockmc.item.Song12LockedItem;
import net.mcreator.hyblockmc.item.Song12IncompleteItem;
import net.mcreator.hyblockmc.item.Song12CompleteItem;
import net.mcreator.hyblockmc.item.Song11LockedItem;
import net.mcreator.hyblockmc.item.Song11IncompleteItem;
import net.mcreator.hyblockmc.item.Song11CompleteItem;
import net.mcreator.hyblockmc.item.Song10LockedItem;
import net.mcreator.hyblockmc.item.Song10IncompleteItem;
import net.mcreator.hyblockmc.item.Song10CompleteItem;
import net.mcreator.hyblockmc.item.SkeletonsHelmetItem;
import net.mcreator.hyblockmc.item.RevenantkeystonetabletT5Item;
import net.mcreator.hyblockmc.item.RevenantkeystonetabletT4Item;
import net.mcreator.hyblockmc.item.RevenantkeystonetabletT3Item;
import net.mcreator.hyblockmc.item.RevenantkeystonetabletT2Item;
import net.mcreator.hyblockmc.item.RevenantkeystonetabletT1Item;
import net.mcreator.hyblockmc.item.RevenantItem;
import net.mcreator.hyblockmc.item.PurplemelodyItem;
import net.mcreator.hyblockmc.item.PinkmelodyItem;
import net.mcreator.hyblockmc.item.MidasStaffT5Item;
import net.mcreator.hyblockmc.item.MidasStaffT4Item;
import net.mcreator.hyblockmc.item.MidasStaffT3Item;
import net.mcreator.hyblockmc.item.MidasStaffT2Item;
import net.mcreator.hyblockmc.item.MidasStaffItem;
import net.mcreator.hyblockmc.item.MelodyTipsTorchItem;
import net.mcreator.hyblockmc.item.LimemelodyItem;
import net.mcreator.hyblockmc.item.LightbluemelodyItem;
import net.mcreator.hyblockmc.item.HyBlockMCiconItem;
import net.mcreator.hyblockmc.item.GuardianChestplateItem;
import net.mcreator.hyblockmc.item.GreenmelodyItem;
import net.mcreator.hyblockmc.item.EnchantedGoldItem;
import net.mcreator.hyblockmc.item.CreeperPantsItem;
import net.mcreator.hyblockmc.item.BookSongLockedItem;
import net.mcreator.hyblockmc.item.BookSongIncompleteItem;
import net.mcreator.hyblockmc.item.BookSongCompleteItem;
import net.mcreator.hyblockmc.item.BluemelodyItem;
import net.mcreator.hyblockmc.item.Adminsword2Item;
import net.mcreator.hyblockmc.item.AdminSword3Item;
import net.mcreator.hyblockmc.item.AdminSword1Item;
import net.mcreator.hyblockmc.HyblockMod;

public class HyblockModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HyblockMod.MODID);
	public static final RegistryObject<Item> ADMIN_SWORD_1 = REGISTRY.register("admin_sword_1", () -> new AdminSword1Item());
	public static final RegistryObject<Item> ADMINSWORD_2 = REGISTRY.register("adminsword_2", () -> new Adminsword2Item());
	public static final RegistryObject<Item> ADMIN_SWORD_3 = REGISTRY.register("admin_sword_3", () -> new AdminSword3Item());
	public static final RegistryObject<Item> TESTDUMMY_SPAWN_EGG = REGISTRY.register("testdummy_spawn_egg", () -> new ForgeSpawnEggItem(HyblockModEntities.TESTDUMMY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SPIDERBOOTS_BOOTS = REGISTRY.register("spiderboots_boots", () -> new SpiderbootsItem.Boots());
	public static final RegistryObject<Item> CREEPER_PANTS_LEGGINGS = REGISTRY.register("creeper_pants_leggings", () -> new CreeperPantsItem.Leggings());
	public static final RegistryObject<Item> GUARDIAN_CHESTPLATE_CHESTPLATE = REGISTRY.register("guardian_chestplate_chestplate", () -> new GuardianChestplateItem.Chestplate());
	public static final RegistryObject<Item> SKELETONS_HELMET_HELMET = REGISTRY.register("skeletons_helmet_helmet", () -> new SkeletonsHelmetItem.Helmet());
	public static final RegistryObject<Item> REVENANTSPAWNERBLOCK = block(HyblockModBlocks.REVENANTSPAWNERBLOCK);
	public static final RegistryObject<Item> TARANTULASPAWNERBLOCK = block(HyblockModBlocks.TARANTULASPAWNERBLOCK);
	public static final RegistryObject<Item> SVENSPAWNERBLOCK = block(HyblockModBlocks.SVENSPAWNERBLOCK);
	public static final RegistryObject<Item> VOIDGLOOMSPAWNERBLOCK = block(HyblockModBlocks.VOIDGLOOMSPAWNERBLOCK);
	public static final RegistryObject<Item> INFERNODEMONSPAWNERBLOCK = block(HyblockModBlocks.INFERNODEMONSPAWNERBLOCK);
	public static final RegistryObject<Item> RIFTSTALKERSPAWNERBLOCK = block(HyblockModBlocks.RIFTSTALKERSPAWNERBLOCK);
	public static final RegistryObject<Item> SLAYERSPAWNERKEYSTONEBLOCK = block(HyblockModBlocks.SLAYERSPAWNERKEYSTONEBLOCK);
	public static final RegistryObject<Item> REVENANTKEYSTONETABLET_T_1 = REGISTRY.register("revenantkeystonetablet_t_1", () -> new RevenantkeystonetabletT1Item());
	public static final RegistryObject<Item> REVENANTKEYSTONETABLET_T_2 = REGISTRY.register("revenantkeystonetablet_t_2", () -> new RevenantkeystonetabletT2Item());
	public static final RegistryObject<Item> REVENANTKEYSTONETABLET_T_3 = REGISTRY.register("revenantkeystonetablet_t_3", () -> new RevenantkeystonetabletT3Item());
	public static final RegistryObject<Item> REVENANTKEYSTONETABLET_T_4 = REGISTRY.register("revenantkeystonetablet_t_4", () -> new RevenantkeystonetabletT4Item());
	public static final RegistryObject<Item> REVENANTKEYSTONETABLET_T_5 = REGISTRY.register("revenantkeystonetablet_t_5", () -> new RevenantkeystonetabletT5Item());
	public static final RegistryObject<Item> MIDAS_STAFF_MOLDEN_GOLD = block(HyblockModBlocks.MIDAS_STAFF_MOLDEN_GOLD);
	public static final RegistryObject<Item> MIDAS_STAFF = REGISTRY.register("midas_staff", () -> new MidasStaffItem());
	public static final RegistryObject<Item> MIDAS_STAFF_T_2 = REGISTRY.register("midas_staff_t_2", () -> new MidasStaffT2Item());
	public static final RegistryObject<Item> MIDAS_STAFF_T_3 = REGISTRY.register("midas_staff_t_3", () -> new MidasStaffT3Item());
	public static final RegistryObject<Item> MIDAS_STAFF_T_4 = REGISTRY.register("midas_staff_t_4", () -> new MidasStaffT4Item());
	public static final RegistryObject<Item> HY_BLOCK_M_CICON = REGISTRY.register("hy_block_m_cicon", () -> new HyBlockMCiconItem());
	public static final RegistryObject<Item> REVENANT_HELMET = REGISTRY.register("revenant_helmet", () -> new RevenantItem.Helmet());
	public static final RegistryObject<Item> REV_HOLLOW_GEN = block(HyblockModBlocks.REV_HOLLOW_GEN);
	public static final RegistryObject<Item> MIDAS_STAFF_T_5 = REGISTRY.register("midas_staff_t_5", () -> new MidasStaffT5Item());
	public static final RegistryObject<Item> ENCHANTED_GOLD = REGISTRY.register("enchanted_gold", () -> new EnchantedGoldItem());
	public static final RegistryObject<Item> ENCHANTED_GOLD_BLOCK = block(HyblockModBlocks.ENCHANTED_GOLD_BLOCK);
	public static final RegistryObject<Item> MELODY_HARP = block(HyblockModBlocks.MELODY_HARP);
	public static final RegistryObject<Item> MELODY_TIPS_TORCH = REGISTRY.register("melody_tips_torch", () -> new MelodyTipsTorchItem());
	public static final RegistryObject<Item> BOOK_SONG_INCOMPLETE = REGISTRY.register("book_song_incomplete", () -> new BookSongIncompleteItem());
	public static final RegistryObject<Item> BOOK_SONG_LOCKED = REGISTRY.register("book_song_locked", () -> new BookSongLockedItem());
	public static final RegistryObject<Item> BOOK_SONG_COMPLETE = REGISTRY.register("book_song_complete", () -> new BookSongCompleteItem());
	public static final RegistryObject<Item> PINKMELODY = REGISTRY.register("pinkmelody", () -> new PinkmelodyItem());
	public static final RegistryObject<Item> YELLOWMELODY = REGISTRY.register("yellowmelody", () -> new YellowmelodyItem());
	public static final RegistryObject<Item> LIMEMELODY = REGISTRY.register("limemelody", () -> new LimemelodyItem());
	public static final RegistryObject<Item> GREENMELODY = REGISTRY.register("greenmelody", () -> new GreenmelodyItem());
	public static final RegistryObject<Item> PURPLEMELODY = REGISTRY.register("purplemelody", () -> new PurplemelodyItem());
	public static final RegistryObject<Item> BLUEMELODY = REGISTRY.register("bluemelody", () -> new BluemelodyItem());
	public static final RegistryObject<Item> LIGHTBLUEMELODY = REGISTRY.register("lightbluemelody", () -> new LightbluemelodyItem());
	public static final RegistryObject<Item> PINK_CLICK_MELODY = block(HyblockModBlocks.PINK_CLICK_MELODY);
	public static final RegistryObject<Item> YELLOW_CLICK_MELODY = block(HyblockModBlocks.YELLOW_CLICK_MELODY);
	public static final RegistryObject<Item> LIME_CLICK_MELODY = block(HyblockModBlocks.LIME_CLICK_MELODY);
	public static final RegistryObject<Item> GREEN_CLICK_MELODY = block(HyblockModBlocks.GREEN_CLICK_MELODY);
	public static final RegistryObject<Item> PURPLE_CLICK_MELODY = block(HyblockModBlocks.PURPLE_CLICK_MELODY);
	public static final RegistryObject<Item> BLUE_CLICK_MELODY = block(HyblockModBlocks.BLUE_CLICK_MELODY);
	public static final RegistryObject<Item> LIGHTBLUE_CLICK_MELODY = block(HyblockModBlocks.LIGHTBLUE_CLICK_MELODY);
	public static final RegistryObject<Item> PINK_FALLING_MELODY = block(HyblockModBlocks.PINK_FALLING_MELODY);
	public static final RegistryObject<Item> YELLOW_FALLING_MELODY = block(HyblockModBlocks.YELLOW_FALLING_MELODY);
	public static final RegistryObject<Item> LIME_FALLING_MELODY = block(HyblockModBlocks.LIME_FALLING_MELODY);
	public static final RegistryObject<Item> GREEN_FALLING_MELODY = block(HyblockModBlocks.GREEN_FALLING_MELODY);
	public static final RegistryObject<Item> PURPLE_FALLING_MELODY = block(HyblockModBlocks.PURPLE_FALLING_MELODY);
	public static final RegistryObject<Item> BLUE_FALLING_MELODY = block(HyblockModBlocks.BLUE_FALLING_MELODY);
	public static final RegistryObject<Item> LIGHTBLUE_FALLING_MELODY = block(HyblockModBlocks.LIGHTBLUE_FALLING_MELODY);
	public static final RegistryObject<Item> SONG_1_INCOMPLETE = REGISTRY.register("song_1_incomplete", () -> new Song1IncompleteItem());
	public static final RegistryObject<Item> SONG_2_INCOMPLETE = REGISTRY.register("song_2_incomplete", () -> new Song2IncompleteItem());
	public static final RegistryObject<Item> SONG_3_INCOMPLETE = REGISTRY.register("song_3_incomplete", () -> new Song3IncompleteItem());
	public static final RegistryObject<Item> SONG_4_INCOMPLETE = REGISTRY.register("song_4_incomplete", () -> new Song4IncompleteItem());
	public static final RegistryObject<Item> SONG_5_INCOMPLETE = REGISTRY.register("song_5_incomplete", () -> new Song5IncompleteItem());
	public static final RegistryObject<Item> SONG_6_INCOMPLETE = REGISTRY.register("song_6_incomplete", () -> new Song6IncompleteItem());
	public static final RegistryObject<Item> SONG_7_INCOMPLETE = REGISTRY.register("song_7_incomplete", () -> new Song7IncompleteItem());
	public static final RegistryObject<Item> SONG_8_INCOMPLETE = REGISTRY.register("song_8_incomplete", () -> new Song8IncompleteItem());
	public static final RegistryObject<Item> SONG_9_INCOMPLETE = REGISTRY.register("song_9_incomplete", () -> new Song9IncompleteItem());
	public static final RegistryObject<Item> SONG_10_INCOMPLETE = REGISTRY.register("song_10_incomplete", () -> new Song10IncompleteItem());
	public static final RegistryObject<Item> SONG_11_INCOMPLETE = REGISTRY.register("song_11_incomplete", () -> new Song11IncompleteItem());
	public static final RegistryObject<Item> SONG_12_INCOMPLETE = REGISTRY.register("song_12_incomplete", () -> new Song12IncompleteItem());
	public static final RegistryObject<Item> SONG_13_INCOMPLETE = REGISTRY.register("song_13_incomplete", () -> new Song13IncompleteItem());
	public static final RegistryObject<Item> SONG_1_COMPLETE = REGISTRY.register("song_1_complete", () -> new Song1CompleteItem());
	public static final RegistryObject<Item> SONG_2_COMPLETE = REGISTRY.register("song_2_complete", () -> new Song2CompleteItem());
	public static final RegistryObject<Item> SONG_3_COMPLETE = REGISTRY.register("song_3_complete", () -> new Song3CompleteItem());
	public static final RegistryObject<Item> SONG_4_COMPLETE = REGISTRY.register("song_4_complete", () -> new Song4CompleteItem());
	public static final RegistryObject<Item> SONG_5_COMPLETE = REGISTRY.register("song_5_complete", () -> new Song5CompleteItem());
	public static final RegistryObject<Item> SONG_6_COMPLETE = REGISTRY.register("song_6_complete", () -> new Song6CompleteItem());
	public static final RegistryObject<Item> SONG_7_COMPLETE = REGISTRY.register("song_7_complete", () -> new Song7CompleteItem());
	public static final RegistryObject<Item> SONG_8_COMPLETE = REGISTRY.register("song_8_complete", () -> new Song8CompleteItem());
	public static final RegistryObject<Item> SONG_9_COMPLETE = REGISTRY.register("song_9_complete", () -> new Song9CompleteItem());
	public static final RegistryObject<Item> SONG_10_COMPLETE = REGISTRY.register("song_10_complete", () -> new Song10CompleteItem());
	public static final RegistryObject<Item> SONG_11_COMPLETE = REGISTRY.register("song_11_complete", () -> new Song11CompleteItem());
	public static final RegistryObject<Item> SONG_12_COMPLETE = REGISTRY.register("song_12_complete", () -> new Song12CompleteItem());
	public static final RegistryObject<Item> SONG_13_COMPLETE = REGISTRY.register("song_13_complete", () -> new Song13CompleteItem());
	public static final RegistryObject<Item> SONG_1_LOCKED = REGISTRY.register("song_1_locked", () -> new Song1LockedItem());
	public static final RegistryObject<Item> SONG_2_LOCKED = REGISTRY.register("song_2_locked", () -> new Song2LockedItem());
	public static final RegistryObject<Item> SONG_3_LOCKED = REGISTRY.register("song_3_locked", () -> new Song3LockedItem());
	public static final RegistryObject<Item> SONG_4_LOCKED = REGISTRY.register("song_4_locked", () -> new Song4LockedItem());
	public static final RegistryObject<Item> SONG_5_LOCKED = REGISTRY.register("song_5_locked", () -> new Song5LockedItem());
	public static final RegistryObject<Item> SONG_6_LOCKED = REGISTRY.register("song_6_locked", () -> new Song6LockedItem());
	public static final RegistryObject<Item> SONG_7_LOCKED = REGISTRY.register("song_7_locked", () -> new Song7LockedItem());
	public static final RegistryObject<Item> SONG_8_LOCKED = REGISTRY.register("song_8_locked", () -> new Song8LockedItem());
	public static final RegistryObject<Item> SONG_9_LOCKED = REGISTRY.register("song_9_locked", () -> new Song9LockedItem());
	public static final RegistryObject<Item> SONG_10_LOCKED = REGISTRY.register("song_10_locked", () -> new Song10LockedItem());
	public static final RegistryObject<Item> SONG_11_LOCKED = REGISTRY.register("song_11_locked", () -> new Song11LockedItem());
	public static final RegistryObject<Item> SONG_12_LOCKED = REGISTRY.register("song_12_locked", () -> new Song12LockedItem());
	public static final RegistryObject<Item> SONG_13_LOCKED = REGISTRY.register("song_13_locked", () -> new Song13LockedItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
